package datamodels;

/* JADX INFO: loaded from: classes9.dex */
public class PaymentResponseModel {
    private String PG_TYPE;
    private String addedon;
    private String amount;
    private String bank_ref_num;
    private String bankcode;
    private String cardCategory;
    private String card_type;
    private String cardnum;
    private String cash_back_percentage;
    private String deduction_percentage;
    private String easepayid;
    private String email;
    private String error;
    private String error_Message;
    private String firstname;
    private String furl;
    private String hash;
    private String issuing_bank;
    private String key;
    private String merchant_logo;
    private String mode;
    private String name_on_card;
    private String net_amount_debit;
    private String payment_source;
    private String phone;
    private String productinfo;
    private String status;
    private String surl;
    private String txnid;
    private String udf1;
    private String udf10;
    private String udf2;
    private String udf3;
    private String udf4;
    private String udf5;
    private String udf6;
    private String udf7;
    private String udf8;
    private String udf9;
    private String unmappedstatus;

    public PaymentResponseModel(String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, String str16, String str17, String str18, String str19, String str20, String str21, String str22, String str23, String str24, String str25, String str26, String str27, String str28, String str29, String str30, String str31, String str32, String str33, String str34, String str35, String str36, String str37, String str38, String str39, String str40) {
        this.name_on_card = str;
        this.deduction_percentage = str2;
        this.net_amount_debit = str3;
        this.txnid = str4;
        this.issuing_bank = str5;
        this.cardCategory = str6;
        this.unmappedstatus = str7;
        this.PG_TYPE = str8;
        this.addedon = str9;
        this.card_type = str10;
        this.error = str11;
        this.cash_back_percentage = str12;
        this.amount = str13;
        this.furl = str14;
        this.productinfo = str15;
        this.email = str16;
        this.status = str17;
        this.bank_ref_num = str18;
        this.hash = str19;
        this.firstname = str20;
        this.surl = str21;
        this.error_Message = str22;
        this.phone = str23;
        this.easepayid = str24;
        this.cardnum = str25;
        this.key = str26;
        this.bankcode = str27;
        this.merchant_logo = str28;
        this.udf10 = str29;
        this.payment_source = str30;
        this.udf1 = str31;
        this.udf3 = str32;
        this.udf2 = str33;
        this.udf5 = str34;
        this.mode = str35;
        this.udf7 = str36;
        this.udf6 = str37;
        this.udf9 = str38;
        this.udf8 = str39;
        this.udf4 = str40;
    }
}
